apiVersion: v1
kind: Service
metadata:
  name: favorite-beer-redis
spec:
  selector:
    app: favorite-beer-redis
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  type: ClusterIP
